### ISSUE TITLE
[BUG] beforeHandle needs to be wrapped in array when used in a global Guard

### ISSUE THREAD

**Issue by axeloehrli** [elysiajs/elysia#156]
I'm trying to use guard method on global schema  to authenticate users
```javascript
app.guard({
    beforeHandle: async ({ cookie, accessToken, set }) => {
      const token = cookie.accessToken
      const user = await accessToken.verify(token)
      if (!user) {
        set.status = 401
        return {
          error: "Unauthorized"
        }
      }
    }
  })

```
 
but for some reason it throws the following error:
```
TypeError: (Y?.beforeHandle??[]).map is not a function. (In '(Y?.beforeHandle??[]).map(X)', '(Y?.beforeHandle??[]).map' is undefined)
      at C1 (/Users/axeloehrli/Projects/ganadexx-api/node_modules/elysia/dist/bun/index.js:8:12945)
      at guard (/Users/axeloehrli/Projects/ganadexx-api/node_modules/elysia/dist/bun/index.js:272:23994)
      at /Users/axeloehrli/Projects/ganadexx-api/src/users.ts:23:3
      at processTicksAndRejections (:1:2602)
```

The solution is to wrap beforeHandle in an array, which i believe is a bug:
```javascript
  beforeHandle: [async ({ cookie, accessToken, set }) => {
      const token = cookie.accessToken
      const user = await accessToken.verify(token)
      if (!user) {
        set.status = 401
        return {
          error: "Unauthorized"
        }
      }
    }]
```

**Comment by HKGx** [comment]
https://github.com/elysiajs/elysia/blob/741ffe7659cf049c8627d30b91cd1f05cfbab53e/src/utils.ts#L68-L71
vs
https://github.com/elysiajs/elysia/blob/741ffe7659cf049c8627d30b91cd1f05cfbab53e/src/utils.ts#L260-L263

Maybe `mergeObjectArray` could take an argument that will apply a mapping after it converts singular items to arrays?

**Comment by SaltyAom** [comment]
Seems not to happen in the latest version, closing.

Feels free to reopen if the issue still persists.

**Comment by hvdson** [comment]
i'm getting this in v0.8.8 currently
