### ISSUE TITLE
mount causes Invalid regular expression: missing )

### ISSUE THREAD

**Issue by deadlinecode** [elysiajs/elysia#193]
Orig discord thread: https://discord.com/channels/1044804142461362206/1153687834809618553

Basically when using `.mount` (current version and v0.6.0) i get the error `Invalid regular expression: missing )` originating from the bun/index.js file.

Don't know why this happens but because of this i can't use `.mount`

**Comment by deadlinecode** [comment]
Here is the full output of the error using Elysia@v0.6.24:
```bash
SyntaxError: Invalid regular expression: missing )
      at s$ (/home/max/svr/node_modules/elysia/dist/bun/index.js:24:337)
      at some (:1:20)
      at d6 (/home/max/svr/node_modules/elysia/dist/bun/index.js:24:2931)
      at add (/home/max/svr/node_modules/elysia/dist/bun/index.js:272:16311)
      at all (/home/max/svr/node_modules/elysia/dist/bun/index.js:272:30046)
      at mount (/home/max/svr/node_modules/elysia/dist/bun/index.js:272:28373)
      at new Server (/home/max/svr/src/Core/Server/Server.ts:7:22)
      at /home/max/svr/src/Core/Core.ts:4:0
19 | )`:`return new ValidationError(
20 | 'response',
21 | response[c.set.status],
22 | ${Y}
23 |
24 | ).toResponse(c.set.headers)`}),s$=($,Y)=>{Y=Y.trimStart(),Y=Y.replaceAll(/^async /g,"");const X=Y.charCodeAt(0)===40||Y.startsWith("function")?Y.slice(Y.indexOf("(")+1,Y.indexOf(")")):Y.slice(0,Y.indexOf("=")-1);if(X==="")return!1;if(X.charCodeAt(0)===123){if(X.includes($))return!0;return!1}if(Y.match(new RegExp(`${X}(.${$}|\\["${$}"\\])`)))return!0;const J=[X];for(let W of Y.matchAll(P9))J.push(W[1]);const Z=new RegExp(`{.*?} = (${J.join("|")})`,"g");for(let[W]of Y.matchAll(Z))if(W.includes(`{ ${$}`)||W.includes(`, ${$}`))return!0;return!1},B$=($,Y,X=[],J="")=>{if(Y.type==="object"){const Z=Y.properties;for(let W in Z){const q=Z[W],M=!J?W:J+"."+W;if(q.type==="object"){B$($,q,X,M);continue}else if(q.anyOf){for(let A of q.anyOf)B$($,A,X,M);continue}if(q.elysiaMeta===$)X.push(M)}if(X.length===0)return null;return X}else if(Y?.elysiaMeta===$){if(J)X.push(J);return"root"}return null},S9=($)=>{if(!$)return;const Y=$?.schema;if(Y&&("anyOf"in Y)){let X=!1;const J=Y.anyOf[0].type;for(let Z of Y.anyOf)if(Z.type!==J){X=!0;break}if(!X)return J}},L9=/(?:return|=>) \S*\(/g,M0=($)=>{if($.constructor.name==="AsyncFunction")return!0;if($.toString().match(L9))return!0;return!1},d6=({method:$,hooks:Y,validator:X,handler:J,handleError:Z,meta:W,onRequest:q,config:M})=>{const A=M.forceErrorEncapsulation||Y.error.length>0||typeof Bun==="undefined"||Y.onResponse.length>0,{composeValidation:D,composeResponseValidation:N}=K9(A),K=Y.onResponse.length?`\n;(async () => {${Y.onResponse.map((j,E)=>`await res${E}(c)`).join(";")}})();\n`:"";let w=A?"try {\n":"";const B=X||$!=="GET"?[J,...Y.transform,...Y.beforeHandle,...Y.afterHandle].map((j)=>j.toString()):[],C=$!=="GET"&&Y.type!=="none"&&(!!X.body||!!Y.type||B.some((j)=>s$("body",j))),S=X.headers||B.some((j)=>s$("headers",j));if(S)w+=D9.toJSON?"c.headers = c.request.headers.toJSON()\n":`c.headers = {}
```

and here is the code that causes it:
```ts
import Elysia from "elysia";

new Elysia().mount("/hono", (req) => new Response());
```
