### ISSUE TITLE
Nested t.Ref Types Causing Errors

### ISSUE THREAD

**Issue by shikanime** [elysiajs/elysia#356]
The `t.Ref` type is not correctly handling nested types when used within an Elysia model, causing errors with both Typebox and Swagger UI generation.

Specifically, when using a `t.Ref` to a nested type, Typebox throws an error about missing $id.

```text                                                                       ^
error: Reference target type must specify an $id
      at new W1 (/home/shika/Source/Sandboxes/elisya-swagger-reproduction/node_modules/elysia/dist/bun/index.js:2:14162)
      at new K6 (:1:32)
      at Throw (/home/shika/Source/Sandboxes/elisya-swagger-reproduction/node_modules/elysia/dist/bun/index.js:2:64630)
      at Ref (/home/shika/Source/Sandboxes/elisya-swagger-reproduction/node_modules/elysia/dist/bun/index.js:2:77340)
      at /home/shika/Source/Sandboxes/elisya-swagger-reproduction/index.ts:8:38
```

Setting the `$id` manually resolves the Typebox error, but Swagger UI still fails to resolve the reference.

```
Resolver error at components.schemas.FlameChasers.items.$ref
Could not resolve reference: undefined undefined
```

To fully resolve the issue, both the model and the `t.Ref` must be explicitly set to the full schema definition path, for instance, `#/components/schemas/FlameChaser`.

```typescript
import { Elysia, t } from "elysia";
import swagger from "@elysiajs/swagger";

const FlameChaser = t.Object(
  {
    name: t.String(),
  },
  { $id: "#/components/schemas/FlameChaser" }
);

const app = new Elysia()
  .use(
    swagger({
      version: "5.10.3",
      documentation: {
        info: {
          title: "Elysian Realm",
          description: "Memories from Previous Era",
          version: "1.0.0",
        },
        externalDocs: {
          url: "https://i.redd.it/pkyaegqqzuk81.png",
          description: "Mobius ❤️ Elysia",
        },
      },
    })
  )
  .model({
    FlameChaser: FlameChaser,
    FlameChasers: t.Array(t.Ref("#/components/schemas/FlameChaser")),
  })
  .post("/flamechaser", ({ body }) => body, {
    body: "FlameChaser",
  })
  .post("/flamechasers", ({ body }) => body, {
    body: "FlameChaser",
  })
  .listen(3000);
```

Do you have an idea of where to look at? I might be insterested to look into the issue.

**Comment by vicimpa** [comment]
The error clearly occurs at the TypeBox level, since it is not sure what to refer to. But the path mapping error clearly stems from the swagger plugin

**Comment by vicimpa** [comment]
The best thing is that Elysia itself collects the specified types for body, headers, params, cookies and query in the model and forwards the refs

**Comment by SaltyAom** [comment]
This should have been fixed by reference model as described in [1.2 release note](https://elysiajs.com/blog/elysia-12.html#typebox-0-34)

Closing as complete
