### ISSUE TITLE
How to get Value Input Body Request

### ISSUE THREAD

**Issue by bobwatcherx** [elysiajs/elysia#5]
How Get Body Value

```
// server.ts
import { Elysia, t} from 'elysia'
import { swagger } from '@elysiajs/swagger'

const app = new Elysia()
    .use(swagger())
    .post("/add",async({body})=>{
        const val = await body
        console.log(val)
    })
    .listen(8080)

export type App = typeof app


console.log(`🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`)

```

**Comment by SaltyAom** [comment]
By default, Elysia will parse the body with `content-type` of `text/plain` and `application/json` and assign to `body`.

Then you can get `body` from `Context.body`:

```typescript
import { Elysia } from 'elysia'

const app = new Elysia()
    .post("/add", ({ body }) => {
        console.log(body)
    })
    .listen(8080)
```

If there you want to support more `content-type`, you can use `onParse`:
```typescript
 app
    .onParse((request, contentType) => {
        if (contentType === 'application/custom-type')
                    return request.text()
    })
```

The returned value will be assigned to `body` in handler.

**Comment by bobwatcherx** [comment]
mengapa masih erorr padahal sudah di rasa benar
```
root@minto-Lenovo-V145-14AST:/home/minto/belajar/elysyaPro/elyapp/manelysia# bun run dev
$ bun run --hot src/index.ts
🦊 Elysia is running at 0.0.0.0:3000
1 | import { Elysia } from 'elysia'
2 | 
3 | const app = new Elysia()
4 |     .get('/', () => 'Hello 1231')
5 |     .post("/add",()=>({body})=>{
6 |         console.log(body)
            ^
TypeError: Right side of assignment cannot be destructured
      at /home/minto/belajar/elysyaPro/elyapp/manelysia/src/index.ts:6:8
      at handle (/home/minto/belajar/elysyaPro/elyapp/manelysia/node_modules/elysia/build/es/index.js:229:17)

```

**Comment by bobwatcherx** [comment]
**SOLVED THANKS**
