### ISSUE TITLE
t.String: String types with patterns must specify a default value

### ISSUE THREAD

**Issue by brianjor** [elysiajs/elysia#514]
### What version of Elysia.JS is running?

0.8.17

### What steps can reproduce the bug?

In a request set the body validations to something like this:
```
body: t.Object({
      name: t.String({
        minLength: 3,
        pattern: '^[a-zA-Z0-9_%-]*$',
      }),
    }),
```
send a request with a `name` of less than 3 in length, but would pass the pattern, ie: "as".

### What is the expected behavior?

Error for name being less than 3 characters long.

### What do you see instead?

```
Error: String types with patterns must specify a default value
    at new TypeBoxError (/home/brian/bun/ftoggle/node_modules/@sinclair/typebox/build/import/type/error/error.mjs:3:10)
    at new ValueCreateError (/home/brian/bun/ftoggle/node_modules/@sinclair/typebox/build/import/value/create/create.mjs:352:10)
    at FromString (/home/brian/bun/ftoggle/node_modules/@sinclair/typebox/build/import/value/create/create.mjs:178:33)
    at <anonymous> (/home/brian/bun/ftoggle/node_modules/@sinclair/typebox/build/import/value/create/create.mjs:142:56)
    at reduce (:1:11)
    at new q (/home/brian/bun/ftoggle/node_modules/elysia/dist/bun/index.js:7:19256)
    at <anonymous> (:107:49)
```

### Additional information

Looks to be caused by the same issue as https://github.com/elysiajs/elysia/issues/309

**Comment by SaltyAom** [comment]
Unable to reproduce on the latest (1.1.9), with the following code:

```ts
const app = new Elysia().get('/', ({ query }) => query, {
	query: t.Object({
		name: t.String({
			minLength: 3,
			pattern: '^[a-zA-Z0-9_%-]*$'
		})
	})
})

app.handle(new Request('http://localhost:3000/?name=123'))
	.then((x) => x.json())
	.then(console.log)
```

If the problem still persist, feel free to reopen the issue. Thanks.
