### ISSUE TITLE
Performance degradation found. Please call Elysia.compile() before using 'fetch'

### ISSUE THREAD

**Issue by Mikey-ShenSu** [elysiajs/elysia#573]
### What version of Elysia.JS is running?

^1.0.9

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

I have created a sample repo, and you may clone and try out.

[Github Repo ](https://github.com/Mikey-ShenSu/elysia-debug)

You may look at the source code of elysia [here](https://github.com/elysiajs/elysia/blob/9a8a285dfdc3b62ed535d44e460d00ced65a8e1f/src/index.ts#L5157)

### What is the expected behavior?

When Nextjs API is called, there should be no error "Performance degradation found. Please call Elysia.compile() before using 'fetch'"

### What do you see instead?

Performance degradation found. Please call Elysia.compile() before using 'fetch'

### Additional information

`bun dev` works fine without the error printing, but when `bun start` after `bun run build`, this happens.

**Comment by Danieljs-codes** [comment]
This happens to me too

**Comment by kidqueb** [comment]
You should call compile on your Elysia instance:

```diff
const apiApp = new Elysia({ prefix: "/api" })
  .get("/", () => "hi")
  .post("/", ({ body }) => body, {
    body: t.Object({
      name: t.String(),
    }),
  })
  .use(countController)
+ .compile();
```

**Comment by Chiji1108** [comment]
I can't deploy an app using Elysia.js with Next.js because of this.

**Comment by Chiji1108** [comment]
Adding `.compile()` will result in this.

```
Collecting page data  ../Users/xxx/.next/server/app/api/[[...slugs]]/route.js:549
`:t+=s+"\n",t+="\n}\n"}return Function("inject",t+=`if(error.constructor.name === "ValidationError" || error.constructor.name === "TransformDecodeError") {
                              ^

EvalError: Code generation from strings disallowed for this context
    at Function (<anonymous>)
    at a6 (/Users/xxx/.next/server/app/api/[[...slugs]]/route.js:549:31)
    at a8 (/Users/xxx/.next/server/app/api/[[...slugs]]/route.js:516:11)
    at e.compile (/Users/xxx/.next/server/app/api/[[...slugs]]/route.js:585:15168)
    at 7406 (/Users/xxx/.next/server/app/api/[[...slugs]]/route.js:609:181)
    at t (/Users/xxx/.next/server/edge-runtime-webpack.js:1:127)
    at t (/Users/xxx/.next/server/app/api/[[...slugs]]/route.js:622:102287)
    at /Users/xxx/.next/server/app/api/[[...slugs]]/route.js:622:102312
    at t.O (/Users/xxx/.next/server/edge-runtime-webpack.js:1:496)
    at /Users/xxx/.next/server/app/api/[[...slugs]]/route.js:622:102329

> Build error occurred
Error: Failed to collect page data for /api/[[...slugs]]
    at /Users/xxx/node_modules/next/dist/build/utils.js:1268:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
   Collecting page data  .error: script "build" exited with code 1
```
