### ISSUE TITLE
I get code: "ERR_INVALID_ARG_TYPE" when I run my Elysia app.

### ISSUE THREAD

**Issue by sepandy** [elysiajs/elysia#698]
### What version of Elysia.JS is running?

1.0.26

### What platform is your computer?

Linux 5.15.0-113-generic x86_64 x86_64

### What steps can reproduce the bug?

I run my Elysia app both with and without docker on my server but I get the following error type error.

### What is the expected behavior?

🦊 Elysia is running at <host>:<port>

### What do you see instead?

Bun v1.1.17 (Linux x64 baseline)
4984 |         },
4985 |         port: options,
4986 |         fetch,
4987 |         error: this.outerErrorHandler
4988 |       };
4989 |       this.server = Bun?.serve(serve);
                                ^
TypeError: 湕捩摯⁥潨瑳慮敭⁳畭瑳愠牬慥祤戠⁥湥潣敤⁤潦⁲潮⹷渊睥唠䱒椨灮瑵⸩潨瑳慮敭猠潨汵⁤潤琠敨琠楲正.敒摡扡敬瑓敲浡椠⁳湩椠癮污摩猠慴整.湉整湲污挠湯楳瑳湥祣攠牲牯›慷捴敨⁲畭整⁸獩氠捯敫⁤桷湥椠
 code: "ERR_INVALID_ARG_TYPE"

      at /app/node_modules/elysia/dist/index.mjs:4989:26
      at /app/src/index.ts:171:3

### Additional information

Running the app on my MacBook works just fine. when I try to run the app from my server I get the error. I tried looking into bun issues and some pointed out it might be because of old kernel version which isn't my case.

**Comment by SaltyAom** [comment]
This is likely because the server lacks avx2, see oven-sh/bun#3312

**Comment by SaltyAom** [comment]
Closing as not related to Elysia, see https://github.com/oven-sh/bun/issues/3312 instead
