### ISSUE TITLE
Support tRPC v11

### ISSUE THREAD

**Issue by exKAZUu** [elysiajs/elysia#769]
### What is the problem this feature would solve?

The current elysia (`1.1.0` of `@elysiajs/trpc`) seems not to support tRPC v11.
If I just bump `@trpc/server` and `@trpc/client` from `10.45.2` to `11.0.0-rc.477`, it causes the following error:

```
# Unhandled error between tests
-------------------------------
41 |     }
42 |     constructor(message, opts){
43 |         const cause = opts?.cause;
44 |         // eslint-disable-next-line @typescript-eslint/ban-ts-comment
45 |         // @ts-ignore https://github.com/tc39/proposal-error-cause
46 |         super(message, {
             ^
TRPCClientError: No "query"-procedure on path "hello"
      at new TRPCClientError (.../node_modules/@trpc/client/dist/TRPCClientError.mjs:46:9)
      at from (.../node_modules/@trpc/client/dist/TRPCClientError.mjs:26:20)
      at .../node_modules/@trpc/client/dist/links/httpBatchLink.mjs:82:56
-------------------------------
```

If you need, I can create a repoduction repo.

### What is the feature you are proposing to solve the problem?

Make `@elysiajs/trpc` support the latest tRPC (v11).

**Comment by exKAZUu** [comment]
Sorry, I should post this to https://github.com/elysiajs/elysia-trpc 🙇‍♂️
