### ISSUE TITLE
tRPC Mutation or Query no found on path

### ISSUE THREAD

**Issue by bibauporto** [elysiajs/elysia#783]
### What steps can reproduce the bug?

Using tRPC adapter.

**Comment by SaltyAom** [comment]
Can you provide more context on your use case?
Elysia doesn't support with tRPC adapter, maybe perhaps you meant tRPC plugin?

**Comment by bibauporto** [comment]
```
export const app = new Elysia()
	.use(
		cors({
			origin: process.env.ORIGIN?.split(','),
		}),
	)
	.use(trpc(appRouter, { createContext }))
	// .all('/trpc/*', async (opts) => {
	// 	const res = await fetchRequestHandler({
	// 		endpoint: '/trpc',
	// 		router: appRouter,
	// 		req: opts.request,
	// 		createContext,
	// 	})
	// 	return res
	// })
```

```

     
          "cookies": [],
          "content": {
            "mimeType": "application/json",
            "size": 795,
            "text": "[{\"error\":{\"message\":\"No \\\"mutation\\\"-procedure on path \\\"users.login\\\"\",\"code\":-32004,\"data\":{\"code\":\"NOT_FOUND\",\"httpStatus\":404,\"stack\":\"TRPCError: No \\\"mutation\\\"-procedure on path \\\"users.login\\\"\\n    at new TRPCError (C:\\\\00_Projects\\\\main\\\\node_modules\\\\@elysiajs\\\\trpc\\\\dist\\\\index.mjs:52:5)\\n    at callProcedure (C:\\\\00_Projects\\\\main\\\\node_modules\\\\@elysiajs\\\\trpc\\\\dist\\\\index.mjs:308:15)\\n    at <anonymous> (C:\\\\00_Projects\\\\main\\\\node_modules\\\\@elysiajs\\\\trpc\\\\dist\\\\index.mjs:859:24)\\n    at inputToProcedureCall (C:\\\\00_Projects\\\\main\\\\node_modules\\\\@elysiajs\\\\trpc\\\\dist\\\\index.mjs:856:37)\\n    at map (:1:11)\\n    at <anonymous> (C:\\\\00_Projects\\\\main\\\\node_modules\\\\@elysiajs\\\\trpc\\\\dist\\\\index.mjs:971:28)\\n    at processTicksAndRejections (:12:39)\",\"path\":\"users.login\"}}}]"
          },
          ```

**Comment by SaltyAom** [comment]
Closing as Elysia tRPC plugin is no longer maintained by Elysia, and is not in Elysia's scope anymore

Please see https://github.com/elysiajs/elysia-trpc/issues/20#issuecomment-2301637191 on how to integrate Elysia with tRPC
