### ISSUE TITLE
Unable to delete property. t.File()

### ISSUE THREAD

**Issue by nodirbekrajaboff** [elysiajs/elysia#793]
### What version of Elysia is running?

latest

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

```ts
import { join } from "path";
import Elysia, { NotFoundError, t } from "elysia";
import sharp from "sharp";
import FormData from "form-data";
import { optimize } from "svgo";

const sourceRoute = new Elysia({ prefix: "/sources" }).get(
  "/images/:name",
  async ({ params: { name }, query: { w, h, q } }) => {
    try {
      const filePath = join(process.cwd(), `/sources/images/${name}`);

      const file = Bun.file(filePath);

      return file;
    } catch (error) {
      console.error(error);
      throw new NotFoundError("The file is not available");
    }
  },
  {
    response: t.File(),
    params: t.Object({
      name: t.String(),
    }),
    query: t.Object({
      w: t.Optional(t.Numeric()),
      h: t.Optional(t.Numeric()),
      q: t.Optional(t.Numeric({ minimum: 0, maximum: 100 })),
    }),
  }
);

export default sourceRoute;
```

```bash
UNKNOWN:  Unable to delete property.
742 |                                                   descriptor &&
743 |                                                   typeof descriptor.get === 'function' &&
744 |                                                   name !== '__proto__'
745 |                                           ) {
746 |                                                   retrievedFields[name] = (value as any)[name]
747 |                                                   delete (currentObj as any)[name]
                                        ^
TypeError: Unable to delete property.
      at F (/*/node_modules/elysia/src/utils.ts:747:35)
      at U (/*/node_modules/elysia/src/utils.ts:758:12)
```

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes

**Comment by SaltyAom** [comment]
Should have been fixed with https://github.com/elysiajs/elysia/commit/2085673c3cb22d131536bbc8ac470061b997379f published under 1.1.8.

Let me know if this fix your issue or not.

**Comment by SaltyAom** [comment]
Close as solved and not reproducible in a recent version
