### ISSUE TITLE
Missing url (required by route.composed) in Context type

### ISSUE THREAD

**Issue by rtritto** [elysiajs/elysia#868]
### What version of Elysia is running?

1.1.19

### What steps can reproduce the bug?

- Create `server.ts`
  ```ts
  import { Elysia } from 'elysia'
  const app = new Elysia()
  app.get('/', ({ query }) => 'hi')  // Note: query in context is required
  const context = {}
  await app.routes[0].composed(context)
  ```
- `bun server.ts`
  ```console
  2 | import { Elysia } from 'elysia'
  3 |
  4 | const app = new Elysia()
  5 | app.get('/', ({ query }) => 'hi')
  6 | const context = {}
                                           ^
  TypeError: undefined is not an object (evaluating 'c.url.slice')
        at handle (56:38)
        at C:\test-route-composed\server.ts:6:21
  ```
- (alternative to previous step) `yarn tsx server.ts`
  ```console
  undefined:56
                                  c.query = parseQueryFromURL(c.url.slice(c.qi + 1))
                                                                    ^
  
  TypeError: Cannot read properties of undefined (reading 'slice')
      at handle (eval at composeHandler (file:///C:/test-route-composed/node_modules/elysia/dist/index.mjs:4926:12), <anonymous>:56:39)   
      at Object.mainHandler [as composed] (file:///C:/test-route-composed/node_modules/elysia/dist/index.mjs:6199:23)
      at <anonymous> (C:\test-route-composed\entry2.ts:22:21)
      at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
      at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)
      at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
  
  Node.js v22.9.0
  ```

### What is the expected behavior?

No error

### What do you see instead?

https://github.com/elysiajs/elysia/blob/93d457b9277f07f1f155ef867af97128130286dc/src/compose.ts#L688-L693

`url` parameter should be added to Context type
https://github.com/elysiajs/elysia/blob/93d457b9277f07f1f155ef867af97128130286dc/src/context.ts#L97

### Additional information

No error with:
```diff
-  const context = {}
+   const context = { url: '/' }
```

**Comment by rtritto** [comment]
In Context, `url` and `path` are the same or one is deprecated?

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
