### ISSUE TITLE
[Composer] failed to generate optimized handler --- error: SyntaxError: Unexpected identifier 'mapCompactResponse'

### ISSUE THREAD

**Issue by dtinth** [elysiajs/elysia#965]
### What version of Elysia is running?

1.2.2

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

```ts
import Elysia from "elysia";

new Elysia()
  .onAfterHandle(() => {
    console.log("after handle");
  })
  .mapResponse((context) => {
    console.log("mapResponse");
    return context.response;
  })
  .get("/", async () => {
    return "ok";
  })
  .listen(3000);
```

Visit localhost:3000

### What is the expected behavior?

Get "ok"

### What do you see instead?

The server crash with this in the log:

```
[Composer] failed to generate optimized handler
---
{
  handler: "async () => {\n  return \"ok\";\n}",
  hooks: {
    start: undefined,
    request: undefined,
    parse: [],
    transform: [],
    beforeHandle: [],
    afterHandle: [ "() => {\n  console.log(\"after handle\");\n}" ],
    mapResponse: [ "(context) => {\n  console.log(\"mapResponse\");\n}" ],
    afterResponse: [],
    trace: [],
    error: [],
    stop: undefined,
    body: undefined,
    headers: undefined,
    params: undefined,
    query: undefined,
    cookie: undefined,
    response: undefined,
    type: undefined,
    detail: {},
    resolve: undefined,
  },
  validator: {
    createBody: [Function: createBody],
    createHeaders: [Function: createHeaders],
    createParams: [Function: createParams],
    createQuery: [Function: createQuery],
    createCookie: [Function: createCookie],
    createResponse: [Function: createResponse],
    body: undefined,
    query: undefined,
    headers: undefined,
    params: undefined,
    cookie: undefined,
    response: undefined,
  },
  definitions: {},
  error: SyntaxError: Unexpected identifier 'mapCompactResponse'
      at <parse> (11:1)
      at Function (native:1:1)
      at composeHandler (/Users/dtinth/Projects/elysia-by-example/node_modules/elysia/src/compose.ts:1925:10)
      at /Users/dtinth/Projects/elysia-by-example/node_modules/elysia/src/index.ts:771:34
      at map (file:///Users/dtinth/Projects/elysia-by-example/node_modules/elysia/dist/bun/index.js:22:65)
,
  fnLiteral: "try{let r=c.response=await handler(c)\nafterHandle[0](c)\nr=c.response\nmr= onMapResponse[0](c)\nif(mr!==undefined)r=c.response=mrreturn mapCompactResponse(r,c.request.signal)\n\n}catch(error){const set=c.set\nif(!set.status||set.status<300)set.status=error?.status||500\nreturn handleError(c,error,true)}",
}
---
```

### Additional information

- Does not happen in v1.1
- Does not happen when `onAfterHandle` is not present
- Does not happen when `{ aot: false }` is added

**Comment by SaltyAom** [comment]
Fixed in https://github.com/elysiajs/elysia/commit/e83daaf23937c94c048ec00f5024f45890df9864, published under 1.2.3
